### ISSUE TITLE
Binary json keys don't deserialize as part of jsonset

### ISSUE THREAD

**Issue by chayim** [RedisLabsModules/redisplus-py#41]
Using the json client with a dictionary containing binary keys fails to serialize - because binary keys cannot be serialized. Example:

```
rc = RedisPlus()
d = {'hello': 'world', b'some': 'value'}
rc.json.jsonset('somekey', '.', d)
```

This is a problem in certain use cases, specifically when keys are fetched from redis. We should provide an optional retry override for json*set (jsonset, jsonsetnx, etc) allowing this serialization to occur prior, should the developer want it.  Failing that the code on the client side would need to look like:

```
rc = RedisPlus()
d = {'hello': 'world', b'some': 'value'}
try:
	rc.json.jsonset('somekey', '.', d)
except redis.exceptions.ResponseError:
    d2 = {}
    for k, v in d.items():
    try:
        d2[k.decode('utf-8')] = v
    except AttributeError:
        d2[k] = v
	rc.json.jsonset('somekey', '.', d2)
```

This seems like something that should be in the client as a _helper_

**Comment by chayim** [comment]
Note: This is the current behaviour of rejson-py as well. But I think we can do better here.

**Comment by AvitalFineRedis** [comment]
What about values?
